
// This file has been generated by the GUI designer. Do not modify.
namespace CBingo
{
	public partial class BomboTest
	{
		public virtual void Build ()
		{
			// Action group CBingo.BomboTest
		}
	}
}
